#!/bin/bash
#Where CHILECOMPRA_RAILS_KEY_LOCATION is the EC2 key file
# CHILECOMPRA_RAILS_DEPLOY_USER is the username on the server
scp -i $CHILECOMPRA_RAILS_KEY_LOCATION -r dist/* $CHILECOMPRA_RAILS_DEPLOY_USER@$CHILECOMPRA_RAILS_SERVER_IP:dist
