//LOGIN/AUTH ACTIONS
    //login
//export const SEND_LOGIN_INFO_SUCCESS = 'SEND_LOGIN_INFO_SUCCESS';

//INPUT FIELD ACTIONS
export const SEARCH_FIELD_INPUT = 'SEARCH_FIELD_INPUT';
export const SELECTION_FIELD_SELECT = 'SELECTION_FIELD_SELECT';
export const DATE_FIELD_SELECT = 'DATE_FIELD_SELECT';
export const AUTOFILLER_INPUT = 'AUTOFILLER_INPUT';
export const RUT_INPUT = 'RUT_INPUT';
export const PICK_ORGANISMO_PUBLICO = 'PICK_ORGANISMO_PUBLICO';
export const COD_LIC_INPUT_CHANGE = 'COD_LIC_INPUT_CHANGE';
export const AUTOFILLER_INPUT_CHANGE = 'AUTOFILLER_INPUT_CHANGE';

// FETCHER ACTIONS
    //fetches organismosPublicos
export const ONLOAD_FETCH_ORG_PUB_SUCCESS = 'ONLOAD_FETCH_ORG_PUB_SUCCESS';
export const ONLOAD_FETCH_ORG_PUB_FAILURE = 'ONLOAD_FETCH_ORG_PUB_FAILURE';
    //fetches estadosLicitacion
export const ONLOAD_FETCH_EST_LIC_SUCCESS = 'ONLOAD_FETCH_EST_LIC_SUCCESS';
export const ONLOAD_FETCH_EST_LIC_FAILURE = 'ONLOAD_FETCH_EST_LIC_FAILURE';
    //fetches the test data 
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS';
    //fetch chilecompra data 
export const FETCH_CHILECOMPRA_DATA_START = 'FETCH_CHILECOMPRA_DATA_START';
export const FETCH_CHILECOMPRA_DATA_SUCCESS = 'FETCH_CHILECOMPRA_DATA_SUCCESS';
export const FETCH_CHILECOMPRA_DATA_FAILURE = 'FETCH_CHILECOMPRA_DATA_FAILURE';


// DISPLAY ACTIONS
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';
export const CHANGE_SEARCH_TYPE = 'CHANGE_SEARCH_TYPE';

//SIGNUP
    //SIGNUP RESULTS
export const USER_SEND_SIGNUP_INFO = 'USER_SEND_SIGNUP_INFO';
export const USER_SEND_SIGNUP_INFO_SUCCESS = 'USER_SEND_SIGNUP_INFO_SUCCESS';
export const USER_SEND_SIGNUP_INFO_FAILURE = 'USER_SEND_SIGNUP_INFO_FAILURE';
    //SIGNUP INPUTS
export const USER_SIGNUP_INPUT_NAME = 'USER_SIGNUP_INPUT_NAME';
export const USER_SIGNUP_INPUT_EMAIL = 'USER_SIGNUP_INPUT_EMAIL';
export const USER_SIGNUP_INPUT_PASSWORD = 'USER_SIGNUP_INPUT_PASSWORD';
export const USER_SIGNUP_INPUT_PASSWORD_CONFIRMATION = 'USER_SIGNUP_INPUT_PASSWORD_CONFIRMATION';

//AUTH ACTIONS
    //INPUT LOGIN INFO
export const USER_LOGIN_EMAIL_INPUT = 'USER_LOGIN_EMAIL_INPUT';
export const USER_LOGIN_PASSWORD_INPUT = 'USER_LOGIN_PASSWORD_INPUT';
    //SEND LOGIN
export const USER_SEND_LOGIN_INFO = 'USER_SEND_LOGIN_INFO';
export const USER_SEND_LOGIN_INFO_SUCCESS = 'USER_SEND_LOGIN_INFO_SUCCESS';
export const USER_SEND_LOGIN_INFO_FAILURE = 'USER_SEND_LOGIN_INFO_FAILURE';
    //REQUEST LOGOUT
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

    //VALIDATE TOKEN
export const USER_VALIDATE_TOKEN = "USER_VALIDATE_TOKEN";
export const USER_VALIDATE_TOKEN_SUCCESS = "USER_VALIDATE_TOKEN_SUCCESS";
export const USER_VALIDATE_TOKEN_FAILURE = "USER_VALIDATE_TOKEN_FAILURE";

//USER
    //MODIFY USER PROFILE ACTIONS
        //API CALL RELATED 
export const USER_MODIFY_PROFILE_DATA = "USER_MODIFY_PROFILE_DATA";
export const USER_MODIFY_PROFILE_DATA_SUCCESS = "USER_MODIFY_PROFILE_DATA_SUCCESS";
export const USER_MODIFY_PROFILE_DATA_FAILURE = "USER_MODIFY_PROFILE_DATA_FAILURE";
        // INPUT HANDLERS
export const USER_MODIFY_PROFILE_DATA_INPUT_NAME = "USER_MODIFY_PROFILE_DATA_INPUT_NAME";
export const USER_MODIFY_PROFILE_DATA_INPUT_EMAIL = "USER_MODIFY_PROFILE_DATA_INPUT_EMAIL";
export const USER_MODIFY_PROFILE_DATA_INPUT_CURRENT_PASSWORD = "USER_MODIFY_PROFILE_DATA_INPUT_CURRENT_PASSWORD";
export const USER_MODIFY_PROFILE_DATA_INPUT_NEW_PASSWORD = "USER_MODIFY_PROFILE_DATA_INPUT_NEW_PASSWORD";
export const USER_MODIFY_PROFILE_DATA_INPUT_NEW_PASSWORD_CONFIRMATION = "USER_MODIFY_PROFILE_DATA_INPUT_NEW_PASSWORD_CONFIRMATION";
export const USER_MODIFY_PROFILE_DATA_INPUT_IMAGE = "USER_MODIFY_PROFILE_DATA_IMAGE";

    //USER RESULTS ACTIONS
export const USER_GET_RESULTS = "USER_GET_RESULTS";
export const USER_GET_RESULTS_SUCCESS = "USER_GET_RESULTS_SUCCESS";
export const USER_GET_RESULTS_FAILURE = "USER_GET_RESULTS_FAILURE";

export const USER_CREATE_RESULTS = "USER_CREATE_RESULTS";
export const USER_CREATE_RESULTS_SUCCESS = "USER_CREATE_RESULTS_SUCCESS";
export const USER_CREATE_RESULTS_FAILURE = "USER_CREATE_RESULTS_FAILURE";

export const USER_UPDATE_RESULTS = "USER_UPDATE_RESULTS";
export const USER_UPDATE_RESULTS_SUCCESS = "USER_UPDATE_RESULTS_SUCCESS";
export const USER_UPDATE_RESULTS_FAILURE = "USER_UPDATE_RESULTS_FAILURE";

export const USER_DELETE_RESULTS = "USER_DELETE_RESULTS";
export const USER_DELETE_RESULTS_SUCCESS = "USER_DELETE_RESULTS_SUCCESS";
export const USER_DELETE_RESULTS_FAILURE = "USER_DELETE_RESULTS_FAILURE";

    //USER QUERIES ACTIONS
export const USER_GET_SEARCHES = "USER_GET_SEARCHES";
export const USER_GET_SEARCHES_SUCCESS = "USER_GET_SEARCHES_SUCCESS";
export const USER_GET_SEARCHES_FAILURE = "USER_GET_SEARCHES_FAILURE";

export const USER_CREATE_SEARCHES = "USER_CREATE_SEARCHES";
export const USER_CREATE_SEARCHES_SUCCESS = "USER_CREATE_SEARCHES_SUCCESS";
export const USER_CREATE_SEARCHES_FAILURE = "USER_CREATE_SEARCHES_FAILURE";

export const USER_UPDATE_SEARCHES = "USER_UPDATE_SEARCHES";
export const USER_UPDATE_SEARCHES_SUCCESS = "USER_UPDATE_SEARCHES_SUCCESS";
export const USER_UPDATE_SEARCHES_FAILURE = "USER_UPDATE_SEARCHES_FAILURE";

export const USER_DELETE_SEARCHES = "USER_DELETE_SEARCHES";
export const USER_DELETE_SEARCHES_SUCCESS = "USER_DELETE_SEARCHES_SUCCESS";
export const USER_DELETE_SEARCHES_FAILURE = "USER_DELETE_SEARCHES_FAILURE"



//MESSAGES
export const MESSAGES_ADD_MESSAGES = "MESSAGES_ADD_MESSAGES";
export const MESSAGES_DELETE_MESSAGES = "MESSAGES_DELETE_MESSAGES";