//LOGIN/AUTH ACTIONS
    //login
export const SEND_LOGIN_INFO_SUCCESS = 'SEND_LOGIN_INFO_SUCCESS';

//INPUT FIELD ACTIONS
export const SEARCH_FIELD_INPUT = 'SEARCH_FIELD_INPUT';
export const SELECTION_FIELD_SELECT = 'SELECTION_FIELD_SELECT';
export const DATE_FIELD_SELECT = 'DATE_FIELD_SELECT';
export const AUTOFILLER_INPUT = 'AUTOFILLER_INPUT';
export const RUT_INPUT = 'RUT_INPUT';
export const PICK_ORGANISMO_PUBLICO = 'PICK_ORGANISMO_PUBLICO';
export const COD_LIC_INPUT_CHANGE = 'COD_LIC_INPUT_CHANGE';
export const AUTOFILLER_INPUT_CHANGE = 'AUTOFILLER_INPUT_CHANGE';

// FETCHER ACTIONS
    //fetches organismosPublicos
export const ONLOAD_FETCH_ORG_PUB_SUCCESS = 'ONLOAD_FETCH_ORG_PUB_SUCCESS';
export const ONLOAD_FETCH_ORG_PUB_FAILURE = 'ONLOAD_FETCH_ORG_PUB_FAILURE';
    //fetches estadosLicitacion
export const ONLOAD_FETCH_EST_LIC_SUCCESS = 'ONLOAD_FETCH_EST_LIC_SUCCESS';
export const ONLOAD_FETCH_EST_LIC_FAILURE = 'ONLOAD_FETCH_EST_LIC_FAILURE';
    //fetches the test data 
export const FETCH_TEST_SUCCESS = 'FETCH_TEST_SUCCESS';
    //fetch chilecompra data 
export const FETCH_CHILECOMPRA_DATA_START = 'FETCH_CHILECOMPRA_DATA_START';
export const FETCH_CHILECOMPRA_DATA_SUCCESS = 'FETCH_CHILECOMPRA_DATA_SUCCESS';
export const FETCH_CHILECOMPRA_DATA_FAILURE = 'FETCH_CHILECOMPRA_DATA_FAILURE';


// DISPLAY ACTIONS
export const TOGGLE_VISIBILITY = 'TOGGLE_VISIBILITY';

