export const FETCH_CHILECOMPRA_DATA = 'FETCH_CHILECOMPRA_DATA';
export const FETCH_ESTADOS_LICITACION = 'FETCH_ESTADOS_LICITACION';
export const FETCH_ORGANISMOS_PUBLICOS = 'FETCH_ORGANISMOS_PUBLICOS';
export const SELECT_PRESELECT_VALUE = 'SELECT_PRESELECT_VALUE';